#!/usr/bin/env bash
# Generates the single-file, agent-consumable docs bundle (the llms-full.txt
# shape) from docs/, AGENTS.md, and every skills/*/SKILL.md, as a build step —
# never hand-maintained, so it cannot drift from the source docs it copies.
# Docs-workflow Step 4b.
#
# Usage:
#   scripts/generate-agent-bundle.sh [output-path]
#
# Default output: llms-full.txt at the repo root.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-"$repo_root/llms-full.txt"}"

{
    echo "# contextdb — agent-consumable documentation bundle"
    echo "# Generated by scripts/generate-agent-bundle.sh — do not edit by hand."
    echo "# Regenerate after any change to AGENTS.md, docs/, or skills/."
    echo

    echo "# ============================================================"
    echo "# AGENTS.md"
    echo "# ============================================================"
    cat "$repo_root/AGENTS.md"
    echo

    for doc in "$repo_root"/docs/*.md; do
        name="$(basename "$doc")"
        echo "# ============================================================"
        echo "# docs/$name"
        echo "# ============================================================"
        cat "$doc"
        echo
    done

    for skill in "$repo_root"/skills/*/SKILL.md; do
        [ -e "$skill" ] || continue
        rel="${skill#"$repo_root"/}"
        echo "# ============================================================"
        echo "# $rel"
        echo "# ============================================================"
        cat "$skill"
        echo
    done
} > "$out"

echo "Wrote $out ($(wc -l < "$out") lines)." >&2
